### ISSUE TITLE
does this ever trigger when doc.filename is good?

### ISSUE THREAD

**Issue by SwissalpS** [vincens2005/lite-xl-gitdiff-highlight#13]
https://github.com/vincens2005/lite-xl-gitdiff-highlight/blob/12ddfa619054dfdd1ed86426d60b569dc536c43e/init.lua#L56

As far as I can tell, ``system.get_file_info`` only returns nil if given path is not a valid directory or file.  
So wouldn't it be best to abort when no file-info is received? Why continue?

git will not find anything if ``system.get_file_info`` didn't.

Which edge-case am I missing?

**Comment by vincens2005** [comment]
I may be stupid

**Comment by SwissalpS** [comment]
> I may be stupid

Unlikely. Sometimes we code and code to figure out a way to get things working and then miss something because we saw it there for so long ... sometimes stray code just sticks :D
