### ISSUE TITLE
Plugin not working, process.start missing?

### ISSUE THREAD

**Issue by tpjg** [vincens2005/lite-xl-gitdiff-highlight#3]
Hi, seems the plugin is not working for me. It always returns "file.... is not in a git repository", which is not correct.

I'm on macOS (Big Sur). I'm not a a Lua developer, but to me it seems `process.start` on line 43 (and 55) is not defined anywhere? Trying to Google for that returns things like `os.Execute` and `io.popen`, so to me it seems this function is probably in a library or file that didn't get included?

p.s. side note I have had various issues on Big Sur due to PATH and plugins not being able to find certain binaries, but don't think this is the case here

**Comment by vincens2005** [comment]
process.start is part of the lite-xl core, so that's not the problem unless you're on an old version. git is probably just not in your PATH

**Comment by tpjg** [comment]
I found it. Interestingly it appears `process.start` does not follow symlinks. On my machine `/usr/local/bin/git` is a symlink to `/usr/local/Cellar/git/2.33.1_1/bin/git` - which is normal on Macs using Homebrew to install all kinds of open source software. To exclude the PATH problem I had already changed line 43 to `/usr/local/bin/git`, still the plugin would not work. Replacing it to the actual binary did solve it. Very counter intuitive, I'll checkout the sources of lite-xl itself and have a look at `process`, maybe file an issue there.

**Comment by tpjg** [comment]
Forget the comment above. I have checked and in the end `execvp` gets called on POSIX systems, that should follow symlinks. It was a coincidence that it worked. Haven't figured out what's happening yet. Sometimes it works, sometimes it doesn't. I'll let you know once I've figured out what's going on. Thanks for responding to issue so far.

FYI, I'm now executing a script instead of git that executes git and logs the output and return code.
```sh
#/bin/zsh
#
echo "mygit starting" >/tmp/mygit.log
echo "Arguments $*" >>/tmp/mygit.log
echo "PWD $PWD" >>/tmp/mygit.log
git $* >>/tmp/mygit.log
CODE=$?
echo "Exit: $CODE" >>/tmp/mygit.log
exit $CODE
```

Interestingly I see that the return code that is returned is actually 0, but for some reason sometimes it will still say "file ___ is not in a git repository", while other times it works.

**Comment by tpjg** [comment]
Okay. Forget the remarks about symlinks and all that sort of thing. Turns out my Mac just needs a bit more time. Changing the wait to 100 (I think it's in milliseconds) consistently works. So I suggest changing line 44 to:

`is_in_repo:wait(100)`

(and I notice the wait for the diff on line 56 is already set to 100).

**Comment by vincens2005** [comment]
alright i'll do that soon

**Comment by tpjg** [comment]
Thanks!
