### ISSUE TITLE
Plugin no longer working

### ISSUE THREAD

**Issue by tionosulis** [vincens2005/lite-xl-gitdiff-highlight#4]
Reinstalling Lite-xl, now plugin no longer working as it used to be, re-downloaded and reinstall the plugin does not fix the problem.
Any help and assistance would be greatly appreciated. :pray: 

Info:
OS : MXLinux 21
DE : Xfce
Lite-XL: Latest

**Comment by vincens2005** [comment]
are there any error messages?

**Comment by tionosulis** [comment]
unfortunately there's no error messasge or helpfull error log. It seem that the plugin just not start or triggered correctly n failled to read git-contained directory. is there any step to troubleshoot or reproduce error log?

**Comment by vincens2005** [comment]
does it say anything about files not being in repos in the log?

**Comment by tionosulis** [comment]
No error log when `init.lua` and `gitdiff.lua` is placed inside 'gitdiff_highlight' folder in `$HOME/.config/lite-xl/plugins` it is should be there right?

Error log showed when placing `init.lua` and `gitdiff.lua` directly on `$HOME/.config/lite-xl/plugins
![image](https://user-images.githubusercontent.com/24350097/143678368-3fa9d43a-95cd-4669-9728-5415ade00abb.png)

**Comment by vincens2005** [comment]
yes, they should be in a folder together. What does the command output of `git diff HEAD` look like?

**Comment by tionosulis** [comment]
`git diff HEAD` returns:
```bash
sulistiono@mxsulis:~
$ cd blog
sulistiono@mxsulis:~/blog
$ git diff HEAD
diff --git a/pages/_document.js b/pages/_document.js
index 9b41fca..2b2ea14 100644
--- a/pages/_document.js
+++ b/pages/_document.js
@@ -8,8 +8,8 @@ class MyDocument extends Document {
 
   render() {
     const meta = {
-      title: 'Next.js Blog Starter Kit',
-      description: 'Clone and deploy your own Next.js portfolio in minutes.',
+      title: 'Test"blog',
+      description: 'Test"s Description,
       image:
         'https://assets.vercel.com/image/upload/q_auto/front/vercel/dps.png'
     }
@@ -24,7 +24,7 @@ class MyDocument extends Document {
           <meta property="og:title" content={meta.title} />
           <meta property="og:image" content={meta.image} />
           <meta name="twitter:card" content="summary_large_image" />
-          <meta name="twitter:site" content="@yourname" />
+          <meta name="twitter:site" content="@test_" />
           <meta name="twitter:title" content={meta.title} />
           <meta name="twitter:description" content={meta.description} />
           <meta name="twitter:image" content={meta.image} />
diff --git a/pages/index.mdx b/pages/index.mdx
index 41459f4..35b1c17 100644
--- a/pages/index.mdx
:

```

**Comment by vincens2005** [comment]
that's weird

**Comment by tionosulis** [comment]
unfortunately the plugin is not working for me. Seem it just won't start and highlight changed lines file tracked by git on my system.

Btw, Thanks for your time n support.

**Comment by tionosulis** [comment]
Open Lite-xl via terminal, open git-contained directory, returns:

```bash
sulistiono@mxsulis:~
$ lite-xl
fatal: not a git repository (or any of the parent directories): .git
```
Could it be caused by the plugin can't access `git` binary file at `/usr/bin` PATH due the file permission? and if it is the case, how to grant the plugin access?

**Comment by tionosulis** [comment]
I find that I can get the plugin works by by firstly `cd`-ing to git-contained directory then opening Lite-xl via terminal , seems that the plugin need full/absolute path.
![image](https://user-images.githubusercontent.com/24350097/144738349-69ec2c9d-dd7e-4acd-9d62-f914b2c8e05d.png)
is there another simple way workaround to make the plugin work by just launch it via lite-xl UI?

Any help and assistance would be greatly appreciated.

**Comment by vincens2005** [comment]
that's strange, because it works on my machine:tm:. I don't really know why it wouldn't work on yours

**Comment by rgrams** [comment]
I have the same issue, though I must say I'm not surprised, since I'm starting Lite-XL from its own folder but accessing files from a completely different directory. I'm assuming `process.start` runs terminal commands in the directory that Lite-XL was started from?

It looks like you can use the `-C` option with `git` commands to run them as if they were in a different folder: https://git-scm.com/docs/git#Documentation/git.txt--Cltpathgt

If I modify the gitdiff-highlight plugin init.lua, around line 60, with this:

```lua
local folder = get_filepath_folder(current_doc) -- custom function I added to test
local is_in_repo = process.start({"git", "-C", folder, "ls-files", "--error-unmatch", current_doc})
```
Then it works—I start getting the diff-highlight bars showing up.
